# Generated by Django 4.0.3 on 2022-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('img', models.CharField(max_length=100000)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100000)),
            ],
        ),
    ]
